import type { Concept } from "@/types";

/** Nhóm concept viral — dữ liệu đồng bộ từ Google Sheet "Concept Viral". */
export const CONCEPT_GROUPS: { id: string; label: string }[] = [
  { id: "value", label: "Giá trị & Thực tiễn" },
  { id: "emotion", label: "Tâm lý & Cảm xúc" },
  { id: "trend", label: "Trend & Thời gian thực" },
  { id: "discover", label: "Khám phá & Độc lạ" },
];

export const CONCEPTS: Concept[] = [
  {
    id: "so-sanh-an-du",
    name: "So sánh / Ẩn dụ",
    emoji: "🔀",
    description: "So Sánh sản phẩm có điểm chung (Cùng phân khúc giá/ Cùng Màu/ Cùng Chất liệu/ Cùng hãng/Công dụng/ Tính năng/ vùng…",
    group: "value",
    promptFragment: "Triển khai theo concept \"So sánh / Ẩn dụ\": So Sánh sản phẩm có điểm chung (Cùng phân khúc giá/ Cùng Màu/ Cùng Chất liệu/ Cùng hãng/Công dụng/ Tính năng/ vùng miền/Thế hệ...) => Nhưng đưa ra điểm khác biệt",
  },
  {
    id: "chu-de-hot",
    name: "Chủ đề Hot",
    emoji: "🌶️",
    description: "Lựa chọn chủ đề Hot cần đạt những yêu cầu sau: - Lý do sinh ra phức tạp - Nhiều tệp biết đến và quan tâm - Thời gian…",
    group: "trend",
    promptFragment: "Triển khai theo concept \"Chủ đề Hot\": Lựa chọn chủ đề Hot cần đạt những yêu cầu sau: - Lý do sinh ra phức tạp - Nhiều tệp biết đến và quan tâm - Thời gian tồn tại lâu - Có tính xã hội Ví dụ: - Tệp HS,SV: Tình yêu học đường, bạo lực học đường, - Tệp giới trẻ: Tình yêu( Phản bội, ngoại tình, người thứ 3- trà xanh...),Công việc: (Định hướng nghề nghiệp, ma cũ bắt nạt ma mới...), truyền động lực... - Tệp già hơn: Hôn nhân( Mẹ chồng nàng…",
  },
  {
    id: "huu-ich-thong-dung",
    name: "Hữu ích, thông dụng",
    emoji: "🛠️",
    description: "Thế nào là 1 content \"Thông dụng\": - Người xem cảm thấy mình đang hiện diện trong content đấy. - Đơn giản, dễ hiểu…",
    group: "value",
    promptFragment: "Triển khai theo concept \"Hữu ích, thông dụng\": Thế nào là 1 content \"Thông dụng\": - Người xem cảm thấy mình đang hiện diện trong content đấy. - Đơn giản, dễ hiểu - Lựa chọn những gì đưa lên content gần gũi, thân thuộc, gắn bó với khách hàng nhất - Mang lại giá trị với tệp khách hàng mục tiêu",
  },
  {
    id: "muon-nguoi-noi-tieng",
    name: "Mượn người nổi tiếng",
    emoji: "🌟",
    description: "Ai là người nổi tiếng: - Người chỉ có followers (Trai xinh, gái đẹp, hiện tượng mạng...): Thông soái ca- Không có sức…",
    group: "discover",
    promptFragment: "Triển khai theo concept \"Mượn người nổi tiếng\": Ai là người nổi tiếng: - Người chỉ có followers (Trai xinh, gái đẹp, hiện tượng mạng...): Thông soái ca- Không có sức ảnh hưởng=> Nổi lên trong 1 thời gian ngắn. - Đại diện cho 1 bộ phận chuyên trải nghiệm nhiều loại sản phẩm khác nhau: KOC - Người có tầm ảnh hưởng tới một bộ phận công chúng nhất định: KOL ( Thông thường là các chuyên gia, những người đứng đầu trong các lĩnh vực, hoặc những người…",
  },
  {
    id: "lon-cau-ky",
    name: "Lớn & cầu kỳ",
    emoji: "💎",
    description: "Tất cả những gì có kích thước lớn, Có giá trị cao, Quý hiếm - Hoặc làm mọi thứ trở nên cầu kì, bày vẽ, làm quá => Đều…",
    group: "discover",
    promptFragment: "Triển khai theo concept \"Lớn & cầu kỳ\": Tất cả những gì có kích thước lớn, Có giá trị cao, Quý hiếm - Hoặc làm mọi thứ trở nên cầu kì, bày vẽ, làm quá => Đều thuộc concept Lớn",
  },
  {
    id: "hanh-trinh",
    name: "Hành trình",
    emoji: "🚀",
    description: "Lựa chọn chủ đề nhiều người mong muốn, khao khát nhưng thường khó thực hiện (VD: Thay đổi ngoại hình \"Giảm cân, làm…",
    group: "discover",
    promptFragment: "Triển khai theo concept \"Hành trình\": Lựa chọn chủ đề nhiều người mong muốn, khao khát nhưng thường khó thực hiện (VD: Thay đổi ngoại hình \"Giảm cân, làm đẹp, chữa mụn, PTTM...\",Khởi nghiệp, sửa nhà, Học tập để đạt được thành tích đáng ngưỡng mộ,...) - Hành trình trải nghiệm gắn với những mốc thời gian cụ thể trong khoảng thời gian trải nghiệm.",
  },
  {
    id: "cam-dong",
    name: "Cảm động",
    emoji: "🥹",
    description: "Những vấn đề mang lại sự cảm động: - Chia ly: Sinh tử, rời xa người thân, đi xa vì mưu sinh, mất mát lớn lao. - Nghịch…",
    group: "emotion",
    promptFragment: "Triển khai theo concept \"Cảm động\": Những vấn đề mang lại sự cảm động: - Chia ly: Sinh tử, rời xa người thân, đi xa vì mưu sinh, mất mát lớn lao. - Nghịch cảnh: Bệnh tật hiểm nghèo, nghèo khó, khuyết tật, bất công, trải qua giai đoạn khó khăn của cuộc đời - Nghèo khó: Thiệt thòi (kì thị, thiếu thốn,,,,), Cuộc sống mưu sinh vất vả,... - Khát vọng giản đơn: Mong muốn nhỏ bé nhưng khó đạt được như được yêu thương, đi học, có một mái…",
  },
  {
    id: "con-so",
    name: "Con số",
    emoji: "🔢",
    description: "Nhìn chung, concpept số là một concept không phải lúc nào cũng sẽ đứng riêng một mình mà thường kèm theo sau đó là sự…",
    group: "value",
    promptFragment: "Triển khai theo concept \"Con số\": Nhìn chung, concpept số là một concept không phải lúc nào cũng sẽ đứng riêng một mình mà thường kèm theo sau đó là sự kết hợp của các concept khác để tăng tính hiệu quả hơn. Đặc biệt nó không giới hạn trong lĩnh vực nào hết. Cấu trúc chung của concept \"số\": Cụm từ dẫn dắt + Con số + Chủ đề hoặc thông điệp / Con số + Chủ đề Lưu ý: Số lẻ như 5, 7, 9 thường tạo cảm giác không quá cố định và khiến…",
  },
  {
    id: "real-time-tin-nong",
    name: "Real Time – Tin nóng",
    emoji: "⚡",
    description: "Đối với concept này, thời gian là yếu tố quan trọng nhất. Càng sớm, càng đón đầu trước thì sẽ càng hiệu quả hơn rất…",
    group: "trend",
    promptFragment: "Triển khai theo concept \"Real Time – Tin nóng\": Đối với concept này, thời gian là yếu tố quan trọng nhất. Càng sớm, càng đón đầu trước thì sẽ càng hiệu quả hơn rất nhiều. Thông thường, nó chỉ được sinh ra khi toàn bộ xã hội hoặc một nhóm đối tượng đủ lớn đều cùng quan tâm chỉ duy nhất 1 sự việc/thông tin nào đó trong một thời gian cố định",
  },
  {
    id: "tranh-cai",
    name: "Tranh cãi",
    emoji: "🔥",
    description: "Mọi người chọn một chủ đề luôn có nhiều góc nhìn và quan điểm khác nhau, đặc biệt trong bài có những quan điểm chạm đến…",
    group: "emotion",
    promptFragment: "Triển khai theo concept \"Tranh cãi\": Mọi người chọn một chủ đề luôn có nhiều góc nhìn và quan điểm khác nhau, đặc biệt trong bài có những quan điểm chạm đến “những chuyện khó” của cuộc sống. Vấn đề này tồn tại nhưng ít khi được bàn đến, vì nó tế nhị hoặc nó khó để giải quyết. Sau đấy đưa ra một quan điểm cá nhân với tính \"mới\". Mới ở đây có thể là góc nhìn mới, cách lập luận mới.",
  },
  {
    id: "ung-ho-so-dong",
    name: "Ủng hộ số đông",
    emoji: "👍",
    description: "Concept \"Ủng hộ Số Đông Dư Luận\" tập trung vào việc tận dụng sức mạnh của đám đông và xu hướng dư luận để gia tăng sự…",
    group: "emotion",
    promptFragment: "Triển khai theo concept \"Ủng hộ số đông\": Concept \"Ủng hộ Số Đông Dư Luận\" tập trung vào việc tận dụng sức mạnh của đám đông và xu hướng dư luận để gia tăng sự chú ý, tính lan tỏa, và sự đồng thuận cho nội dung. Ý tưởng cốt lõi là đi theo hoặc đồng thuận với ý kiến mà số đông đang quan tâm hoặc ủng hộ, từ đó kích thích sự đồng cảm, chia sẻ, và thảo luận từ khán giả.",
  },
  {
    id: "chuyen-te-nhi",
    name: "Chuyện tế nhị",
    emoji: "💋",
    description: "Nguyên tắc của concept này đấy là làm sao để có thể kích hoạt được các giác quan của con người nhằm đánh vào sự ham…",
    group: "emotion",
    promptFragment: "Triển khai theo concept \"Chuyện tế nhị\": Nguyên tắc của concept này đấy là làm sao để có thể kích hoạt được các giác quan của con người nhằm đánh vào sự ham muốn, khao khát có được, chiếm hữu được.",
  },
  {
    id: "bat-mi-bi-mat",
    name: "Bật mí bí mật",
    emoji: "🕵️",
    description: "Nguyên tắt của concept bật mí bí mật theo kiểu kết hợp của người nổi tiếng thì căn bản là phải tạo cho người ta cảm…",
    group: "discover",
    promptFragment: "Triển khai theo concept \"Bật mí bí mật\": Nguyên tắt của concept bật mí bí mật theo kiểu kết hợp của người nổi tiếng thì căn bản là phải tạo cho người ta cảm giác tò mò, gay cấn. Miễn làm sao mà khiến họ ít ngờ tới, giúp vỡ lẽ ra một sự thật nào đấy. Chủ đề càng nhiều người quan tâm/càng nổi tiếng thì càng tốt",
  },
  {
    id: "cuoc-thi-gameshow",
    name: "Cuộc thi / Gameshow",
    emoji: "🏆",
    description: "Thông thường các câu thách đố này sẽ liên quan trực tiếp đến insight đối tượng khách hàng mà các bạn đang hướng tới là…",
    group: "discover",
    promptFragment: "Triển khai theo concept \"Cuộc thi / Gameshow\": Thông thường các câu thách đố này sẽ liên quan trực tiếp đến insight đối tượng khách hàng mà các bạn đang hướng tới là chủ yếu. Nhằm mục đích để thỏa mãn \"nhu cầu thể hiện cá nhân\" của mỗi người",
  },
  {
    id: "nguoc-doi-nghich-ly",
    name: "Ngược đời nghịch lý",
    emoji: "🙃",
    description: "Thực hiện ở một góc nhìn \"ngược\" lại hoàn toàn so với mặc định vốn có",
    group: "discover",
    promptFragment: "Triển khai theo concept \"Ngược đời nghịch lý\": Thực hiện ở một góc nhìn \"ngược\" lại hoàn toàn so với mặc định vốn có",
  },
  {
    id: "vung-mien-dan-toc",
    name: "Vùng miền dân tộc",
    emoji: "🗺️",
    description: "Vẫn là tập trung đánh vào yếu tố nhu cầu muốn được xem những cái đẹp của con người. Hầu như những bạn ở dân tộc có nét…",
    group: "discover",
    promptFragment: "Triển khai theo concept \"Vùng miền dân tộc\": Vẫn là tập trung đánh vào yếu tố nhu cầu muốn được xem những cái đẹp của con người. Hầu như những bạn ở dân tộc có nét đẹp riêng vốn có, kín đáo thì vẫn dễ khiến cho những người khác giới đều cảm thấy thích",
  },
  {
    id: "duy-nhat",
    name: "Duy nhất",
    emoji: "🥇",
    description: "Đưa ra một đối tượng, chủ thể mà chỉ có người đó mới là người đối xử cực kì tốt/không điều kiện Thông thường nó sẽ liên…",
    group: "discover",
    promptFragment: "Triển khai theo concept \"Duy nhất\": Đưa ra một đối tượng, chủ thể mà chỉ có người đó mới là người đối xử cực kì tốt/không điều kiện Thông thường nó sẽ liên quan đến tình cảm gia đình nhiều hơn",
  },
  {
    id: "canh-bao",
    name: "Cảnh báo",
    emoji: "⚠️",
    description: "Tính xác thực: Thông tin phải chính xác, có nguồn gốc rõ ràng, tránh gây hoang mang hoặc đưa tin sai lệch. - Tính cấp…",
    group: "emotion",
    promptFragment: "Triển khai theo concept \"Cảnh báo\": Tính xác thực: Thông tin phải chính xác, có nguồn gốc rõ ràng, tránh gây hoang mang hoặc đưa tin sai lệch. - Tính cấp thiết: Đề cập đến những vấn đề có ảnh hưởng trực tiếp hoặc tiềm ẩn nguy cơ cao đến người xem. (Gây hại sức khỏe, Mất tài sản, Ảnh hưởng tinh thần/ tâm lý,...) - Tính hữu ích: Cung cấp giải pháp, hướng dẫn hoặc cách phòng tránh cụ thể, thiết thực . - Thông tin cảnh báo hướng đến…",
  },
  {
    id: "diy-tu-lam",
    name: "DIY – Tự làm",
    emoji: "🧰",
    description: "Tập trung vào ''hướng dẫn'' hoặc ''cung cấp giải pháp'' để mọi người tự làm/ cải tiến những sản phẩm, công việc thay vì…",
    group: "value",
    promptFragment: "Triển khai theo concept \"DIY – Tự làm\": Tập trung vào ''hướng dẫn'' hoặc ''cung cấp giải pháp'' để mọi người tự làm/ cải tiến những sản phẩm, công việc thay vì mua sẵn hay thuê người khác làm. ( Bánh xà phòng, đồ dùng trong gia đình, Quần áo, đồ trang trí,...) - Sản phẩm tạo ra mang lại giá trị với người dùng, người xem.",
  },
  {
    id: "du-lieu-nghien-cuu",
    name: "Dữ liệu & nghiên cứu",
    emoji: "📊",
    description: "Đem đến những thông tin giá trị dựa trên nghiên cứu & dữ liệu được xác thực. => Có sức thuyết phục cao, tăng cường sự…",
    group: "value",
    promptFragment: "Triển khai theo concept \"Dữ liệu & nghiên cứu\": Đem đến những thông tin giá trị dựa trên nghiên cứu & dữ liệu được xác thực. => Có sức thuyết phục cao, tăng cường sự tín nhiệm đến vị trí người xem, độc giả. Tiêu chuẩn chọn nguồn Dữ liệu và Nghiên cứu phù hợp: -Chọn dữ liệu, nghiên cứu đáng tin cậy: - Nguồn uy tín: Có chuyên môn cao+ (được nhà nước cấp phép), thông tin lấy từ ''Đối tượng có uy tín/có tầm ảnh hưởng lớn'' đối với tệp khách hàng…",
  },
  {
    id: "phi-thuong",
    name: "Phi thường",
    emoji: "🤩",
    description: "Concept \"Phi Thường\" tập trung vào những câu chuyện, hành động, hoặc thành tích vượt xa khỏi khả năng thông thường của…",
    group: "discover",
    promptFragment: "Triển khai theo concept \"Phi thường\": Concept \"Phi Thường\" tập trung vào những câu chuyện, hành động, hoặc thành tích vượt xa khỏi khả năng thông thường của con người. - Nội dung thuộc concept này thường gợi cảm hứng mạnh mẽ, truyền tải thông điệp về sự nỗ lực, ý chí phi thường và tinh thần hy sinh cao cả.",
  },
  {
    id: "bat-trend",
    name: "Bắt trend",
    emoji: "🎵",
    description: "Mọi nội dung thuộc concept Trend đều có tính chất hữu hạn về thời gian, đa phần sẽ bùng phát và lan truyền mạnh mẽ khi…",
    group: "trend",
    promptFragment: "Triển khai theo concept \"Bắt trend\": Mọi nội dung thuộc concept Trend đều có tính chất hữu hạn về thời gian, đa phần sẽ bùng phát và lan truyền mạnh mẽ khi xuất hiện đúng thời điểm. Dù được tạo ra theo cách có chủ đích, dựa vào thời điểm cố định, hay vô tình, cốt lõi là nội dung vẫn phải kích thích sự yêu thích và hưởng ứng từ đám đông",
  },
  {
    id: "phat-kien-moi",
    name: "Phát kiến mới",
    emoji: "💡",
    description: "Phát kiến phải mang yếu tố mới mẻ và độc đáo (khác biệt so với những gì đã tồn tại trước đó) và đồng thời mang lại giá…",
    group: "discover",
    promptFragment: "Triển khai theo concept \"Phát kiến mới\": Phát kiến phải mang yếu tố mới mẻ và độc đáo (khác biệt so với những gì đã tồn tại trước đó) và đồng thời mang lại giá trị thực tiễn rõ ràng, có khả năng ứng dụng cao trong đời sống",
  },
  {
    id: "chuyen-la-do-day",
    name: "Chuyện lạ đó đây",
    emoji: "🌍",
    description: "Nội dung cần tập trung vào những sự việc, hiện tượng hoặc câu chuyện kỳ quặc, khác thường đến mức gây bất ngờ hoặc tò…",
    group: "discover",
    promptFragment: "Triển khai theo concept \"Chuyện lạ đó đây\": Nội dung cần tập trung vào những sự việc, hiện tượng hoặc câu chuyện kỳ quặc, khác thường đến mức gây bất ngờ hoặc tò mò mạnh mẽ. Điểm nhấn nằm ở tính độc lạ và hiếm gặp, tạo cảm giác \"không thể tin nổi\" nhưng vẫn phải đảm bảo tính xác thực hoặc gợi cảm giác có thể xảy ra",
  },
  {
    id: "deo-bam",
    name: "Đeo bám",
    emoji: "📌",
    description: "Tập trung khai thác và bám đuổi một sự kiện/nhân vật cho đến cùng đến khi nào một trong hai có dấu hiệu \"đuối\" thì mới…",
    group: "trend",
    promptFragment: "Triển khai theo concept \"Đeo bám\": Tập trung khai thác và bám đuổi một sự kiện/nhân vật cho đến cùng đến khi nào một trong hai có dấu hiệu \"đuối\" thì mới thôi. Thông thường mục tiêu bám đuổi sẽ có hai kiểu: hoặc là muốn triệt để đối phương một cách tiêu cực hoặc tích cực",
  },
  {
    id: "thuc-giuc",
    name: "Thúc giục",
    emoji: "⏰",
    description: "Concept này nhấn mạnh vào sự cấp bách và hậu quả nghiêm trọng nếu không hành động kịp thời. Nội dung cần tạo cảm giác…",
    group: "emotion",
    promptFragment: "Triển khai theo concept \"Thúc giục\": Concept này nhấn mạnh vào sự cấp bách và hậu quả nghiêm trọng nếu không hành động kịp thời. Nội dung cần tạo cảm giác nguy cơ rõ ràng hoặc đánh vào nỗi sợ của khán giả, từ đó thúc đẩy họ hành động ngay để tránh rủi ro hoặc mất mát. Tuy nhiên, cần đảm bảo thông điệp trung thực, tránh phóng đại hoặc gây hoang mang không cần thiết",
  },
  {
    id: "ky-quac-ngo-ngan",
    name: "Kỳ quặc ngớ ngẩn",
    emoji: "🤪",
    description: "Nội dung tập trung vào những khám phá, phát minh, hoặc ý tưởng mới lạ nhưng mang tính kỳ quặc, khó tin, hoặc không thực…",
    group: "discover",
    promptFragment: "Triển khai theo concept \"Kỳ quặc ngớ ngẩn\": Nội dung tập trung vào những khám phá, phát minh, hoặc ý tưởng mới lạ nhưng mang tính kỳ quặc, khó tin, hoặc không thực tế. Điểm nhấn nằm ở sự ngớ ngẩn, kỳ quặc của các phát kiến và cũng không có khả năng ứng dụng thực tế dài hạn",
  },
  {
    id: "chung-nhan",
    name: "Chứng nhận",
    emoji: "✅",
    description: "Concept \"Chứng nhận\" tập trung vào việc làm nổi bật uy tín, thành tựu, hoặc sự công nhận của cá nhân, tổ chức, hoặc sản…",
    group: "value",
    promptFragment: "Triển khai theo concept \"Chứng nhận\": Concept \"Chứng nhận\" tập trung vào việc làm nổi bật uy tín, thành tựu, hoặc sự công nhận của cá nhân, tổ chức, hoặc sản phẩm thông qua các giải thưởng, danh hiệu, hoặc kết quả đã được xác minh. Nội dung nhấn mạnh vào tính đáng tin cậy, nổi bật, và xứng đáng, giúp khán giả cảm thấy tin tưởng và ấn tượng với điều được chứng nhận",
  },
  {
    id: "ufo-bi-an",
    name: "UFO – Bí ẩn",
    emoji: "🛸",
    description: "Concept \"UFO\" tập trung vào các nội dung bí ẩn, không xác định, và kích thích trí tò mò, thường xoay quanh những câu…",
    group: "discover",
    promptFragment: "Triển khai theo concept \"UFO – Bí ẩn\": Concept \"UFO\" tập trung vào các nội dung bí ẩn, không xác định, và kích thích trí tò mò, thường xoay quanh những câu chuyện hoặc hiện tượng kỳ lạ, không thể giải thích hoặc chưa được chứng minh. Mục tiêu là tạo cảm giác huyền bí, gợi sự tò mò và tranh luận, đồng thời khuyến khích khán giả tưởng tượng hoặc đưa ra phán đoán riêng",
  },
  {
    id: "hay-cuon",
    name: "Hay & cuốn",
    emoji: "👌",
    description: "Nội dung phải mang lại sự bất ngờ, hấp dẫn và kích thích sự tham gia của khán giả, khiến họ cảm thấy hứng thú, vỗ đùi…",
    group: "value",
    promptFragment: "Triển khai theo concept \"Hay & cuốn\": Nội dung phải mang lại sự bất ngờ, hấp dẫn và kích thích sự tham gia của khán giả, khiến họ cảm thấy hứng thú, vỗ đùi và thốt lên khen \"Hay\". Yếu tố \"hay\" được thể hiện qua sự lôi cuốn trong cách tổ chức, độ thú vị của thử thách, và cảm giác thỏa mãn khi người tham gia hoặc người xem trải nghiệm nội dung",
  },
  {
    id: "tot-dep-bat-ngo",
    name: "Tốt đẹp bất ngờ",
    emoji: "🎁",
    description: "Đó là nội dung tập trung vào quá trình phát triển hoặc biến đổi bất ngờ trong một hành trình, từ những khó khăn, định…",
    group: "emotion",
    promptFragment: "Triển khai theo concept \"Tốt đẹp bất ngờ\": Đó là nội dung tập trung vào quá trình phát triển hoặc biến đổi bất ngờ trong một hành trình, từ những khó khăn, định kiến, hoặc khởi đầu tiêu cực đến một kết quả tích cực, đầy cảm hứng. Yếu tố \"hành trình\" giúp làm nổi bật sự cố gắng, nỗ lực, và sự \"tốt đẹp một cách bất ngờ\" chính là làm khán giả ngạc nhiên/cảm động với kết quả cuối cùng.",
  },
  {
    id: "van-de-giai-phap-tuong-tuong",
    name: "Vấn đề & giải pháp tưởng tượng",
    emoji: "🧩",
    description: "Tập trung vào việc tạo ra các tình huống hoặc kịch bản chưa xảy ra nhưng có thể xảy ra dựa trên xu hướng, vấn đề hiện…",
    group: "discover",
    promptFragment: "Triển khai theo concept \"Vấn đề & giải pháp tưởng tượng\": Tập trung vào việc tạo ra các tình huống hoặc kịch bản chưa xảy ra nhưng có thể xảy ra dựa trên xu hướng, vấn đề hiện tại, hoặc trí tưởng tượng sáng tạo. Nội dung mang tính logic, kích thích trí tò mò của khán giả, đồng thời mở ra góc nhìn thú vị hoặc giải pháp mới cho các vấn đề trong tương lai",
  },
  {
    id: "nhan-qua-lien-ket",
    name: "Nhân quả liên kết",
    emoji: "🔗",
    description: "Concept này tập trung vào việc làm rõ mối liên hệ logic giữa nguyên nhân và kết quả để truyền tải ý nghĩa hoặc thông…",
    group: "emotion",
    promptFragment: "Triển khai theo concept \"Nhân quả liên kết\": Concept này tập trung vào việc làm rõ mối liên hệ logic giữa nguyên nhân và kết quả để truyền tải ý nghĩa hoặc thông điệp sâu sắc. Nội dung phải có sự liên kết chặt chẽ, gây tò mò ở phần nguyên nhân và mang lại kết quả bất ngờ hoặc ấn tượng, từ đó thu hút sự chú ý và tạo sự đồng cảm hoặc hứng thú cho khán giả",
  },
  {
    id: "ma-kinh-di",
    name: "Ma – Kinh dị",
    emoji: "👻",
    description: "Khi kết hợp giữa ma (hoặc yếu tố tâm linh) và giải pháp trong tưởng tượng, nội dung thường xoay quanh việc đưa ra các…",
    group: "discover",
    promptFragment: "Triển khai theo concept \"Ma – Kinh dị\": Khi kết hợp giữa ma (hoặc yếu tố tâm linh) và giải pháp trong tưởng tượng, nội dung thường xoay quanh việc đưa ra các giải pháp giả định, phi thực tế nhưng sáng tạo",
  },
  {
    id: "giai-thuong",
    name: "Giải thưởng",
    emoji: "🎖️",
    description: "Tập trung vào việc làm nổi bật những thành tựu, giải thưởng, hoặc danh hiệu mà nhân vật/câu chuyện đạt được. - Những…",
    group: "discover",
    promptFragment: "Triển khai theo concept \"Giải thưởng\": Tập trung vào việc làm nổi bật những thành tựu, giải thưởng, hoặc danh hiệu mà nhân vật/câu chuyện đạt được. - Những thành tựu, giải thưởng,..: Thường không dễ dàng có được. - Điểm nhấn chính: sự ngưỡng mộ, tự hào, và giá trị mà giải thưởng mang lại, - Đặc biệt: truyền cảm hứng cho người xem bằng cách làm nổi bật sự nỗ lực, hành trình và ý nghĩa của thành tựu đó.",
  },
  {
    id: "hai-huoc",
    name: "Hài hước",
    emoji: "😂",
    description: "Tập trung vào việc làm cho khán giả cười, cảm thấy thoải mái, hoặc gợi lên sự thích thú thông qua các yếu tố vui nhộn…",
    group: "emotion",
    promptFragment: "Triển khai theo concept \"Hài hước\": Tập trung vào việc làm cho khán giả cười, cảm thấy thoải mái, hoặc gợi lên sự thích thú thông qua các yếu tố vui nhộn, bất ngờ. - Nội dung hài hước thường dễ lan tỏa nhờ khả năng kích thích cảm xúc tích cực, giúp khán giả kết nối dễ dàng hơn.",
  },
];

export const getConcept = (id: string): Concept | undefined =>
  CONCEPTS.find((c) => c.id === id);

export const conceptsByGroup = () =>
  CONCEPT_GROUPS.map((g) => ({
    ...g,
    items: CONCEPTS.filter((c) => c.group === g.id),
  }));
